### ISSUE TITLE
Update to be compatible with new frontend

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-remote-video#24]
The new Dart-based frontend breaks the API formerly used for content to display on the frontend. Content type plugins that don't reduce to a built-in content type will need to be updated by @bamnet.

**Comment by gbprz** [comment]
Made a first pass at this in #27 which was just merged. 

My approach was to add a concerto_frontend_plugins hook in Concerto (just after the frontend plugin hook that includes the entire vulcanized frontend) and render the polymer element as a partial. Let me know if there was anything else you guys had in mind for this.
