### ISSUE TITLE
HTTPVideo via IFRAME results in size issues and video controls showing

### ISSUE THREAD

**Issue by mjhca** [concerto/concerto-remote-video#25]
The capability to embed any **HTTP video** is excellent but there are a couple of issues this introduced.

Currently, the HTTP video URL is passed to an IFRAME SRC as opposed to generating the actual **`<video>`** tag within the plugin.  The result is that the browser will implicitly create its own document fragment within the IFRAME, containing a `<video>` tag, to render the video.  Since this is browser-specific behavior, results will be unpredictable.  

For example, on Webkit-based (i.e. Chrome) browsers:

* **Flickering** occurs as video loads because the generated HTML5 `<video>` tag does not specify a width/height.  Element is initially one size, then once video metadata loads, it resizes to the native video width
* **Video does not scale** to full IFRAME width; it plays at its native width/height
* **`controls`** attribute on `<video>` tag is generated by the browser, so (unwanted) controls appear as the video loads and then fade as the video begins playing

A simple solution is likely for the plugin to directly generate the `<video>` tag (as opposed to IFRAME) for HTTPVideo.  Video tag should specify width=100% and NOT have a `controls` attribute.

**Comment by augustf** [comment]
I tested in the latest Concerto a typical sample video from http://camendesign.com/code/video_for_everybody/test.html in Firefox, Chrome, and Safari on OSX 10.10. 

Flickering: I was unable to reproduce any sort of flickering in any of the three browsers.

Scaling: In Safari and Chrome, the video did not properly scale to fit the video area and was inside a large black box. In Firefox, scaling worked as expected.

Controls: In Safari, the control palette kept flickering and it took several tries to play the video. All three browsers, however, did show the controls during load and unload.

**Comment by 007lva** [comment]
I had the same problem, but [this](https://github.com/concerto/concerto-remote-video/pull/33) works to me

**Comment by daberkow** [comment]
I am seeing the same issues with Chrome not scaling the video. If I load a self hosted video in Chrome it then loads with a black box around it. Do you have any fixes in mind for this?
