### ISSUE TITLE
YouTube Data API no longer supported

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-remote-video#26]
The YouTube Data API that Concerto uses is no longer supported.

![687474703a2f2f692e696d6775722e636f6d2f61586f485a46612e706e67](https://cloud.githubusercontent.com/assets/12512/7253949/ea7213ae-e80d-11e4-8a80-c8a65df10bca.png)

**Comment by xd1936** [comment]
Check out [youtube.com/devicesupport](https://youtube.com/devicesupport) for more info.

v2 has been depreciated, and [v3](https://developers.google.com/youtube/v3/) is the latest version to use.

**Comment by augustf** [comment]
Looking over the API specification at https://developers.google.com/youtube/v3/ , it would appear that the new API requires a project API key and has quotas for certain operations. If I'm reading correctly, that suggests we would need to have a mechanism for users to configure an API key themselves.

**Comment by augustf** [comment]
After discussion this with @bamnet, the approach we're favoring is having a ConcertoConfig for the user's YouTube API key. If it isn't populated, we won't show YouTube as an option.

 I took a pass at implementing this, but the structure of this plugin (being a "content-type" plugin and not a "regular" plugin) was quite confusing and I didn't get anywhere.

**Comment by augustf** [comment]
In continuing to work on this, I think I may turn towards the video_info gem (https://github.com/thibaudgg/video_info). In addition to require two completely separate API calls (one to get basic metadata and another for duration), the rubbish Youtube v3 API now encodes the duration using ISO8601 durations, which requires its own gem to decode at present. So either way, we're in for another gem.

Video_info apparently doesn't require the API key for getting content metadata (not sure about embedding yet) and works with a bunch of other services as well with a nice interface to it. Having mostly finished the YouTube v3 mess anyway, I may do a branch for each one.

**Comment by augustf** [comment]
With the merge of #26, this is somewhat resolved. With the video_info gem, some of the more broken behavior the deprecation introduced (stubbed durations and broken titles) in Youtube's API has been worked around. But given the impracticality of having everyone get an API key, we'll in the future resort to either bypassing the v3 API (screen scraping or other unauthenticated access) or just deprecating YouTube.
