### ISSUE TITLE
1.2 breaks 2.3.5 release

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-remote-video#41]
When attempting to build 2.3.5, I got an issue with the RSS and video plugins I could not resolve. It didn't come up during testing or build but only for users upgrading their Concerto. This broke the Concerto VM severely. The message was "Downloading concerto_simple_rss-1.2 revealed dependencies not in the API or
the lockfile". 
![screen shot 2017-08-14 at 8 45 19 pm](https://user-images.githubusercontent.com/12512/29298267-8577722e-8134-11e7-9eb8-33201b5055b2.png)
I was forced to revert the entire release, as the error could not be resolved on any of my installations.

**Comment by mfrederickson** [comment]
@augustf from the screenshot above, it looks like the rss plugin worked ok, or am I missing something?

**Comment by mfrederickson** [comment]
Just documenting my findings so far....
Concerto master branch seems to bundle fine on development machine.
![selection_213](https://user-images.githubusercontent.com/473165/29627822-d98e6eec-87df-11e7-8779-1ac80c41cd79.png)

**Comment by mfrederickson** [comment]
It looks like none of the changes to the Gemfile.lock are making it into the release (and thus into the deb package).  I thought changes to master would be included in the draft release...  I guess I have to assign a new tag to the draft release, then publish the release for the tag to be created, then change it back to a draft release.

**Comment by mfrederickson** [comment]
I updated the release (by giving it a new tag) and it now includes your commits and mine, and the concerto-full package installs fine on my test concerto vm.  Please try again and let me know.  The release name 2.3.5 doesn't match the tag 2.3.5.1 and I didn't know if you wanted to change that or not.

**Comment by mfrederickson** [comment]
BTW, I resolved the bundler errors by the recommended route of removing the Gemfile.lock and letting it get rebuilt.  rake test then showed that an airbrake update was breaking so I locked it at it's previous major version.  I updated my bundler, and rebuilt the Gemfile.lock, rake tested, repackaged, copied the full deb to my vm and installed it via dpkg -i, and all worked fine.

**Comment by mfrederickson** [comment]
@augustf interesting-- when I edited the release to a prerelease with the new tag, the public activity says that you created that tag.... anyway, might want to uncheck the prerelease checkbox once you're happy with it.
